"""Change models for better usability

Revision ID: 2eb3b883f4d5
Revises: a62cb61db793
Create Date: 2025-11-03 19:41:12.844143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eb3b883f4d5'
down_revision = 'a62cb61db793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.String(length=50), nullable=False))
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('lastname')
        batch_op.drop_column('name')

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
